### ISSUE TITLE
Parse integers, Golang

### ISSUE THREAD

**Issue by MarErm27** [Highload-fun/issues#12]
Hi! I was wondering if I can ask here. When I use the expression below I got ```Error: died or killed```, why this could be happening?
 ```fmt.Sscan(scanner.Text(), &n)```

**Comment by sergei-svistunov** [comment]
It could be in case of you've reached memory limit or your code has crashed.
Probably it could be killed by timeout and the platform hasn't save it. I'll check the timeout label.

**Comment by MarErm27** [comment]
@sergei-svistunov 
Thank you, you are right, it just works too slow
For example
https://play.golang.org/p/XrOlrp63V9M
