### ISSUE TITLE
AVX512 support

### ISSUE THREAD

**Issue by vmunoz82** [Highload-fun/issues#18]
Hi, is there a list of extensions supported by the judge machine?

I tried to run code compiled with -mavx512f -mavx512vbmi and it crashed.

**Comment by sergei-svistunov** [comment]
Hi. You can hover `i` badge in CPU. There is the CPU info:
![image](https://user-images.githubusercontent.com/1058692/209088862-82d4f87c-9445-4465-b240-af2257385b3d.png)

**Comment by vmunoz82** [comment]
Thank you, I really miss that!
