### ISSUE TITLE
Use nightly Rust

### ISSUE THREAD

**Issue by kevinheavey** [Highload-fun/issues#19]
Nightly Rust has some stuff that's pretty useful, like std::simd

**Comment by sergei-svistunov** [comment]
Hi.
Nightly builds are unstable. the performance can be different day by day.
Let's wait the features in stable releases and as soon as the release will be published in the [RELEASES](https://raw.githubusercontent.com/rust-lang/rust/master/RELEASES.md) file, you can select it on the site.
