### ISSUE TITLE
Cannot use Huge Pages feature

### ISSUE THREAD

**Issue by matsuoka-601** [Highload-fun/issues#20]
Hello.

[This link](https://github.com/Highload-fun/platform/wiki/How-to-use-MMAP-to-optimize-data-reading) says that Huge Pages feature is available, so I submitted the code below. But it returns `Error: Exit with code 1: mmap`. Any advice on how to use Huge Pages feature? Thanks in advance.
```c++
#include <iostream>
#include <sys/mman.h>

int main() {
    void* ptr = mmap(0, 10, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS | MAP_HUGETLB, -1, 0);
    if (ptr == MAP_FAILED) {
        std::cerr << "mmap";
        exit(1);
    }
    return 0;
}
```

**Comment by sergei-svistunov** [comment]
Try to use the `madvise` function.

**Comment by matsuoka-601** [comment]
That worked. Thank you!
