### ISSUE TITLE
Rust: allow unstable features with RUSTC_BOOTSTRAP

### ISSUE THREAD

**Issue by WardBrian** [Highload-fun/issues#22]
I've already seen #21. I understand the reason to not want to use nightly completely. 

BUT! There is a environment variable you can set [called `RUSTC_BOOTSTRAP`](https://rustc-dev-guide.rust-lang.org/building/bootstrapping/what-bootstrapping-does.html?highlight=rustc_bootstrap#complications-of-bootstrapping) which allows you to use `#[feature...` on stable compiler versions. This would mostly be useful to unlock std::simd. 

Obviously it's not intended to be used for general purposes, but then again, neither is mmaping STDIN ;)

**Comment by sergei-svistunov** [comment]
It's already on: `RUSTC_BOOTSTRAP=1`

**Comment by WardBrian** [comment]
Thanks!
