### ISSUE TITLE
Add button to clean localstorage

### ISSUE THREAD

**Issue by a-poptsov** [Highload-fun/issues#6]
Please add button to reset current snippet to the default one

**Comment by sergei-svistunov** [comment]
Temporary workaround:
1. clean editor
2. try to submit empty code
3. refresh page

**Comment by a-poptsov** [comment]
or

1. go to development tools
2. select application tab
3. clean localstorage of a specific task

**Comment by sergei-svistunov** [comment]
![image](https://user-images.githubusercontent.com/1058692/117125884-c7017200-ada2-11eb-9161-20a5964f907d.png)
